### Get Index
GET http://localhost:3001/

### Get Menus
GET http://localhost:3001/menus

### Get Menu
GET http://localhost:3001/menus/18

### Save Menu
POST http://localhost:3001/menus 
content-type: application/json

{
    "name": "na",
    "description": "",
    "price": 4.5,
    "category_id": 3
}

### Update Menu
PUT http://localhost:3001/menus/19
content-type: application/json

{
    "name": "Naskun telor",
    "description": "Waffle with ice cream",
    "price": 4.5,
    "category_id": 3
}

### Delete Menu
DELETE http://localhost:3001/menus/19

### Get Categories
GET http://localhost:3001/categories

### Get Category
GET http://localhost:3001/categories/2

### Get Menus by Category
GET http://localhost:3001/categories/3/menus

### Save Category
POST http://localhost:3001/categories
content-type: application/json

{
    "name": "Coffee"
}

### Update Category
PUT http://localhost:3001/categories/7
content-type: application/json

{
    "name": "Western"
} 

### Delete Category
DELETE http://localhost:3001/categories/4